import Link from "next/link";

export const metadata = { title: "Privacy Policy · Skill Tracker" };

const sections = [
  {
    title: "Who runs this",
    body: (
      <p>
        Skill Tracker is a personal project run by an individual. For any privacy question,
        write to <a href="mailto:remi.azar.13@gmail.com" style={{ color: "var(--amber-dim)" }}>remi.azar.13@gmail.com</a>.
      </p>
    ),
  },
  {
    title: "What data is collected",
    body: (
      <ul className="list-disc pl-5 space-y-1">
        <li>Account: your name, email address and a hashed password (never stored in clear text).</li>
        <li>Optional profile picture, if you upload one.</li>
        <li>Your content: skills, practice sessions, projects, notes, durations and dates.</li>
        <li>Technical: a session cookie to keep you logged in, plus the IP address and browser type recorded with each login session.</li>
      </ul>
    ),
  },
  {
    title: "Why",
    body: <p>Only to run the app: log you in and show you your own skills and statistics. There is no advertising, no analytics and no selling of data.</p>,
  },
  {
    title: "Where it is stored",
    body: (
      <p>
        The app is hosted on Vercel and the database is hosted on Neon. These providers process
        data on my behalf and may run servers outside the European Union.
      </p>
    ),
  },
  {
    title: "Cookies and local storage",
    body: (
      <p>
        One essential cookie keeps you signed in. Your browser also stores which notifications you
        dismissed. Neither is used for tracking.
      </p>
    ),
  },
  {
    title: "Third-party requests",
    body: (
      <p>
        Some skill pictures are loaded from external image sites, and your default avatar is
        generated by DiceBear from an anonymous identifier (not your email). Like any image
        request, this reveals your IP address to those sites.
      </p>
    ),
  },
  {
    title: "Your rights",
    body: (
      <p>
        You can access, correct, export and delete your data. Export is available in Settings.
        To delete your account and all its data, email me and I will do it. If you are in the EU,
        you can also complain to your data protection authority (in France, the CNIL).
      </p>
    ),
  },
  {
    title: "Retention and changes",
    body: (
      <p>
        Your data is kept until you ask for deletion. If this policy changes, the date below will
        be updated.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <main className="min-h-screen px-6 py-10" style={{ color: "var(--ink)" }}>
      <div className="mx-auto max-w-2xl">
        <Link href="/" className="btn-ghost">← BACK TO HOME</Link>

        <h1 className="display text-4xl mt-6 mb-2">Privacy Policy</h1>
        <p className="mono text-[11px] tracking-widest mb-8" style={{ color: "var(--ink-faint)" }}>
          LAST UPDATED: 30 SEPTEMBER 2026
        </p>

        <div className="space-y-5">
          {sections.map((s) => (
            <section key={s.title} className="card">
              <h2 className="label-head text-[17px] mb-2">{s.title}</h2>
              <div className="text-sm space-y-2" style={{ color: "var(--ink-dim)" }}>
                {s.body}
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}